// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Provide a helpful warning so developers know why the app might fail
  // early if they forgot to set the VITE_SUPABASE_* environment variables.
  // We still create a client with empty strings so imports don't throw,
  // but this makes debugging clearer in the browser console.
  // eslint-disable-next-line no-console
  console.warn(
    "Supabase URL or publishable key is not set (VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY). Supabase client will be created with empty credentials.",
  );
}

// Use localStorage only when running in the browser.
const storage = typeof window !== "undefined" ? localStorage : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage as any,
    persistSession: true,
    autoRefreshToken: true,
  },
});