// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a safe Supabase client that won't crash if env vars are missing
let supabaseClient;
try {
  if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
    supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } else {
    console.warn('Supabase environment variables are not set. Some features may not work.');
    // Create a mock client to prevent crashes
    supabaseClient = createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  // Create a fallback client
  supabaseClient = createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = supabaseClient;